
[webservers]
web-1 ansible_host=93.77.183.115 fqdn=fhmtilkmlh3kpuko1ibj.auto.internal
web-2 ansible_host=89.169.143.123 fqdn=fhmn318rh7km12m3sr1q.auto.internal

[databases]
main ansible_host= fqdn=fhmc7f0kc0r70n1psgb7.auto.internal
replica ansible_host= fqdn=fhmq9q8ks7gk2i9lvevv.auto.internal

[storage]
storage ansible_host=93.77.180.202 fqdn=fhmijgbkukrblh2dopgc.auto.internal
